version: 2
project_name: vaultui
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - vendor: "Mohamed EL BOUCHIR"
    homepage: "https://github.com/mohamed-el-bouchir/vaultui"
    maintainer: "Mohamed EL BOUCHIR"
    description: "A secure, minimal, and interactive TUI note-taking application built in Go."
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

brews:
  - repository:
      owner: mohamed-el-bouchir
      name: homebrew-tap
    description: "A secure, minimal, and interactive TUI note-taking application built in Go."
    homepage: "https://github.com/mohamed-el-bouchir/vaultui"
